default:
  image: archlinux:latest

stages:
  - prepare
  - build
  - test

prepare job:
  stage: prepare
  script:
    - pacman -Syq --noconfirm gcc cmake boost boost-libs gtest
    - cd /usr/src/gtest
    - mkdir build
    - cd build
    - cmake .. -GCMAKE_BUILD_TYPE=Release
    - make install -j10
    - cd -

build job:
  stage: build
  script:
    - mkdir build
    - cd build
    - CXX=/usr/lib/gcc-snapshot/bin/g++ CC=/usr/lib/gcc-snapshot/bin/gcc cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . -- -j10

test job:
  stage: test
  script:
    - ./webpptest
