# see https://hub.docker.com/_/gcc/
image: gcc

stages:
  - build
  - test

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install ninja cmake libboost-dev libboost-program-options-dev libgtest-dev
    - mkdir /usr/src/googletest/googletest/build
    - cd /usr/src/googletest/googletest/build
    - cmake -DCMAKE_BUILD_TYPE=Release -G "Ninja" ..
    - ninja install
    - cd -
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -G "Ninja" ..
  script:
    - ninja
  artifacts:
    paths:
      - build
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      cache:
        paths:
          - "build/*"

# run tests using the binary built before
test:
  stage: test
  script:
    - ./webpptest
  artifacts:
    paths:
      - build

