default:
  image: archlinux:latest
  before_script:
    - sudo pacman -Sq --noconfirm gcc cmake boost boost-libs gtest
    - sudo mkdir /usr/src/googletest/googletest/build
    - cd /usr/src/googletest/googletest/build
    - sudo cmake ..
    - sudo make install -j10
    - sudo rm -rf /usr/src/googletest/googletest/build
    - cd -

stages:
  - build
  - test

job 1:
  stage: build
  script:
    - mkdir build
    - cd build
    - CXX=/usr/lib/gcc-snapshot/bin/g++ CC=/usr/lib/gcc-snapshot/bin/gcc cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . -- -j10

job 2:
  stage: test
  script:
    - ./webpptest
