default:
  image: archlinux:latest
  before_script:
    - pacman -Syuq --noconfirm
    - pacman -Sq --noconfirm gcc cmake boost boost-libs gtest
    - sudo mkdir /usr/src/googletest/googletest/build
    - cd /usr/src/googletest/googletest/build
    - cmake ..
    - make install -j10
    - rm -rf /usr/src/googletest/googletest/build
    - cd -

stages:
  - build
  - test

build job:
  stage: build
  script:
    - mkdir build
    - cd build
    - CXX=/usr/lib/gcc-snapshot/bin/g++ CC=/usr/lib/gcc-snapshot/bin/gcc cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . -- -j10

test job:
  stage: test
  script:
    - ./webpptest
